version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=11111111
      - DB_NAME=kanban_db
      - DB_PORT=5432
      - JWT_SECRET=tk7P+qGfiE3Zrz7UFFanE1sLJ7AK4lf/2lRwaap6z4Q=
    networks:
      - kanban-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=11111111
      - POSTGRES_DB=kanban_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanban-network

volumes:
  postgres_data:

networks:
  kanban-network:
    driver: bridge